channels:
- conda-forge
dependencies:
- python=3.12.1
- pip<=23.2.1
- pip:
  - mlflow==2.16.0
  - cloudpickle==3.0.0
  - feature-engine==1.8.1
  - numpy==1.26.4
  - pandas==2.2.2
  - psutil==6.0.0
  - scikit-learn==1.5.1
  - scipy==1.14.1
name: mlflow-env
